### PR TITLE
External variables support (closes #514)

### LINKED ISSUE #514: Not generate tests with extern variable [BUG]
**To Reproduce**
Try generate tests for next code

```cpp
int abs(int a){
    if (a < 0) {
        return -1 * a;
    }
    return a;
}

#define MAX_INDEX 10

extern unsigned g_arrayNumber[MAX_INDEX];

unsigned GetNum(unsigned index)
{
    return g_arrayNumber[index];
}
```

Test not generated

in UTBot logs
`2022-10-24 13:22:25.130 [utbot-B29P      ]        RunKleeTask.cpp:60       1| .   .   KLEE: ERROR: Unable to load symbol(g_arrayNumber) while initializing globals`

### PR DESCRIPTION
**Pull request by Lana243**
Closes #514 

To fix the problem extern variable declaration was added to KLEE wrapper and gtest file.

### CODE REVIEW

**Comment by alexey-utkin** [comment]
Seems currenly we get a problem with tests
```
[  FAILED  ] 36 tests, listed below:
[  FAILED  ] Regression_Test.Incomplete_Array_Type
[  FAILED  ] Regression_Test.Global_Char_Array
[  FAILED  ] Regression_Test.Global_Array_Of_Pointers
[  FAILED  ] Server_Test.Globals
[  FAILED  ] Syntax_Test.Pointer_Return_Test_1
[  FAILED  ] Syntax_Test.Pointer_Return_Test_2
[  FAILED  ] Syntax_Test.Pointer_Return_Test_3
[  FAILED  ] Syntax_Test.Return_Long_Long_Array
[  FAILED  ] Syntax_Test.Structs_With_Arrays_Parameter_Test_1
[  FAILED  ] Syntax_Test.Structs_With_Arrays_Return_Test_1
[  FAILED  ] Syntax_Test.Struct_With_Double_Pointer
[  FAILED  ] Syntax_Test.Return_Const_Char_Pointer_1
[  FAILED  ] Syntax_Test.Return_Const_Char_Pointer_2
[  FAILED  ] Syntax_Test.Return_Const_Struct_Pointer_1
[  FAILED  ] Syntax_Test.Return_Int_Array
[  FAILED  ] Syntax_Test.Return_Void2D
[  FAILED  ] Syntax_Test.Return_Null_Pointer
[  FAILED  ] Syntax_Test.Return_Null_Struct
[  FAILED  ] Syntax_Test.Multi_Array_1
[  FAILED  ] Syntax_Test.Multi_Pointer_1
[  FAILED  ] Syntax_Test.Struct_With_Multi_Array
[  FAILED  ] Syntax_Test.Multi_Pointer_Struct
[  FAILED  ] Syntax_Test.Return_Struct_With_Array
[  FAILED  ] Syntax_Test.Sum_Matrix
[  FAILED  ] Syntax_Test.Count_Dashes
[  FAILED  ] Syntax_Test.Accept_Const_Int_Pointer_Pointer
[  FAILED  ] Syntax_Test.UnnamedTypeUnionField
[  FAILED  ] Syntax_Test.UnnamedTypeStructField
[  FAILED  ] Syntax_Test.AnonymousUnionField
[  FAILED  ] Syntax_Test.AnonymousStructField
[  FAILED  ] Syntax_Test.Pass_Forward_Decl
[  FAILED  ] Syntax_Test.Duplicate_Struct
[  FAILED  ] Syntax_Test.Global_Unnamed_Variable
[  FAILED  ] Syntax_Test.bitfields_check_simple_signed_str
[  FAILED  ] Syntax_Test.bitfields_check_fields_bounds
[  FAILED  ] Syntax_Test.bitfields_check_unnamed
```

File: server/src/printers/KleePrinter.cpp [hunk 1]
```diff
@@ -143,6 +143,15 @@ fs::path KleePrinter::writeTmpKleeFile(
 
     writeAccessPrivateMacros(typesHandler, tests, false);
 
+    CollectionUtils::apply(tests.externVariables, [this](const Tests::TypeAndVarName &var) {
```
Comment (ladisgin) [inline server/src/printers/KleePrinter.cpp:146]: Same as server/src/printers/TestsPrinter.cpp:66

Comment (ladisgin) [inline server/src/printers/KleePrinter.cpp:146]: useless apply

**Review by ladisgin — CHANGES_REQUESTED** [review]

**Review by ladisgin — APPROVED** [review]

**Review by sava-cska — APPROVED** [review]
