### PR TITLE
fix: show run icons only for files in tests directory

### LINKED ISSUE #394: [BUG] CLion plugin: run icons are placed for tests outside utbot tests directory
**Description**
If you open any cpp file with word `TEST` plugin will show a run icon near it, though it is not a test that can be run by UTBot. 

**To Reproduce**
1. Open the any project
2. Open cpp file with word 'TEST'

**Expected behavior**
Run icon should be placed if it is located inside utbot tests directory

**Actual behavior**
Run icon is placed although the file is not in utbot tests directory

### PR DESCRIPTION
**Pull request by vol0n**
closes #394 
To prevent run icons from showing in non-utbot-tests, add a condition to show them only in tests dir and in files which names contain word `test`.

### CODE REVIEW

File: clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/testsResults/UTBotTestRunLineMarkerProvider.kt [hunk 1]
```diff
@@ -51,7 +55,13 @@ class UTBotTestRunLineMarkerProvider : LineMarkerProvider {
                 return UTBotRunWithCoverageLineMarkerInfo(element, message, getStatusIcon(element))
             }
 
-            private fun getStatusIcon(element: PsiElement): Icon {
+            private fun isElementInTestFileGeneratedByUTBot(element: PsiElement) =
+                element.containingFile.virtualFile.localPath.let {
```
Comment (alexey-utkin) [inline clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/testsResults/UTBotTestRunLineMarkerProvider.kt:59]: Is this the same way we check the 'test' status in VSCode plugin?

Comment (vol0n) [reply clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/testsResults/UTBotTestRunLineMarkerProvider.kt:59]: https://github.com/UnitTestBot/UTBotCpp/blob/32c0298667653f493d5c5543f60b527da61b2c11/vscode-plugin/src/codelens/codelensProvider.ts#L36

not exactly, in VSCode code lenses are placed in any file that are in tests directory. I think it is not quite good, because if you open any file and type in 'TEST' then code lenses for running utbot tests will appear, that's why I added an extra condition

Comment (alexey-utkin) [reply clion-plugin/src/main/kotlin/org/utbot/cpp/clion/plugin/ui/testsResults/UTBotTestRunLineMarkerProvider.kt:59]: Not `lenses` but `gutter to run a test`.

**Review by alexey-utkin — APPROVED** [review]
